// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module Arty100TDDRHarness(
  input sys_clock,
  input jtag_jtag_TCK,
  input jtag_jtag_TMS,
  input jtag_jtag_TDI,
  output jtag_jtag_TDO,
  output uart_txd,
  input  uart_rxd,
  output uart2_txd,
  input  uart2_rxd,
  inout  gpio_gpio_0,
        gpio_gpio_1,
        gpio_gpio_2,
        gpio_gpio_3,
        gpio_gpio_4,
        gpio_gpio_5,
        gpio_gpio_6,
        gpio_gpio_7,
        sdio_spi_clk,
        sdio_spi_cs,
  // SDIO
        sdio_spi_dat_0,
        sdio_spi_dat_1,
        sdio_spi_dat_2,
        sdio_spi_dat_3,
        flash_qspi_sck,
        flash_qspi_cs,
        flash_qspi_dq_0,
        flash_qspi_dq_1,
        flash_qspi_dq_2,
        flash_qspi_dq_3,
  input reset
);

  wire       _harnessBinderReset_catcher_io_sync_reset;	// @[ResetCatchAndSync.scala:39:28]
  wire       _plusarg_reader_out;	// @[PlusArg.scala:80:11]
  wire       _ram_io_ser_in_valid;	// @[TSIHarness.scala:24:24]
  wire [3:0] _ram_io_ser_in_bits;	// @[TSIHarness.scala:24:24]
  wire       _ram_io_ser_out_ready;	// @[TSIHarness.scala:24:24]
  wire       _chiptop0_serial_tl_bits_in_ready;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_serial_tl_bits_out_valid;	// @[HasHarnessInstantiators.scala:82:40]
  wire [3:0] _chiptop0_serial_tl_bits_out_bits;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_jtag_TDO;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_sck;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_0_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_0_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_0_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_1_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_1_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_1_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_2_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_2_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_2_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_3_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_3_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_dq_3_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_spi_0_cs_0;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_uart_0_txd;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_uart_1_txd;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_0_o_oval;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_0_o_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_0_o_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_0_o_pue;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_0_o_ds;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_0_o_ps;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_0_o_ds1;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_0_o_poe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_1_o_oval;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_1_o_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_1_o_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_1_o_pue;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_1_o_ds;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_1_o_ps;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_1_o_ds1;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_1_o_poe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_2_o_oval;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_2_o_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_2_o_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_2_o_pue;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_2_o_ds;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_2_o_ps;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_2_o_ds1;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_2_o_poe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_3_o_oval;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_3_o_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_3_o_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_3_o_pue;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_3_o_ds;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_3_o_ps;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_3_o_ds1;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_3_o_poe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_4_o_oval;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_4_o_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_4_o_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_4_o_pue;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_4_o_ds;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_4_o_ps;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_4_o_ds1;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_4_o_poe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_5_o_oval;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_5_o_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_5_o_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_5_o_pue;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_5_o_ds;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_5_o_ps;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_5_o_ds1;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_5_o_poe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_6_o_oval;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_6_o_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_6_o_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_6_o_pue;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_6_o_ds;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_6_o_ps;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_6_o_ds1;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_6_o_poe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_7_o_oval;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_7_o_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_7_o_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_7_o_pue;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_7_o_ds;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_7_o_ps;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_7_o_ds1;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_gpio_0_pins_7_o_poe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_sck;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_0_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_0_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_0_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_1_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_1_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_1_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_2_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_2_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_2_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_3_o;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_3_ie;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_dq_3_oe;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _chiptop0_qspi_0_cs_0;	// @[HasHarnessInstantiators.scala:82:40]
  wire       _reset_ibuf_O;	// @[Harness.scala:81:26]
  wire       _bundleIn_0_dq_3_i_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_dq_2_i_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_dq_1_i_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_dq_0_i_a2b_b;	// @[Util.scala:30:21]
  wire       _a2b_14_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_pins_7_i_ival_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_pins_6_i_ival_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_pins_5_i_ival_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_pins_4_i_ival_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_pins_3_i_ival_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_pins_2_i_ival_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_pins_1_i_ival_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_pins_0_i_ival_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_rxd_a2b_1_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_rxd_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_srst_n_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_TDI_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_TMS_a2b_b;	// @[Util.scala:30:21]
  wire       _bundleIn_0_TCK_a2b_b;	// @[Util.scala:30:21]
  wire       _sys_clock_ibufg_O;	// @[ClockOverlay.scala:32:22]
  wire       _harnessSysPLL_clk_out1;	// @[XilinxShell.scala:76:55]
  wire       _harnessSysPLL_locked;	// @[XilinxShell.scala:76:55]
  wire       _dutGroup_auto_out_clock;	// @[ClockGroup.scala:31:15]
  wire       _dutGroup_auto_out_reset;	// @[ClockGroup.scala:31:15]
  wire       _dutWrangler_auto_out_clock;	// @[Harness.scala:31:31]
  wire       _dutWrangler_auto_out_reset;	// @[Harness.scala:31:31]
  reg        bundleIn_0_dq_1_i_REG;	// @[SDIOOverlay.scala:19:39]
  reg        bundleIn_0_dq_1_i_REG_1;	// @[SDIOOverlay.scala:19:31]
  always @(posedge _dutWrangler_auto_out_clock) begin	// @[Harness.scala:31:31]
    bundleIn_0_dq_1_i_REG <= _a2b_14_b;	// @[SDIOOverlay.scala:19:39, Util.scala:30:21]
    bundleIn_0_dq_1_i_REG_1 <= bundleIn_0_dq_1_i_REG;	// @[SDIOOverlay.scala:19:{31,39}]
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        bundleIn_0_dq_1_i_REG = _RANDOM_0[2];	// @[SDIOOverlay.scala:19:39]
        bundleIn_0_dq_1_i_REG_1 = _RANDOM_0[3];	// @[SDIOOverlay.scala:19:{31,39}]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  ResetWrangler dutWrangler (	// @[Harness.scala:31:31]
    .auto_in_clock  (_dutGroup_auto_out_clock),	// @[ClockGroup.scala:31:15]
    .auto_in_reset  (_dutGroup_auto_out_reset),	// @[ClockGroup.scala:31:15]
    .auto_out_clock (_dutWrangler_auto_out_clock),
    .auto_out_reset (_dutWrangler_auto_out_reset)
  );
//  ClockGroup dutGroup (	// @[ClockGroup.scala:31:15]
//    .auto_in_member_0_clock (_harnessSysPLL_clk_out1),	// @[XilinxShell.scala:76:55]
//    .auto_in_member_0_reset (~_reset_ibuf_O),	// @[Harness.scala:81:26, :86:22, PLLFactory.scala:78:{20,35}, XilinxShell.scala:76:55]
//    .auto_out_clock         (_dutGroup_auto_out_clock),
//    .auto_out_reset         (_dutGroup_auto_out_reset)
//  );
//  harnessSysPLL harnessSysPLL (	// @[XilinxShell.scala:76:55]
//    .clk_in1  (_sys_clock_ibufg_O),	// @[ClockOverlay.scala:32:22]
//    .reset    (~_reset_ibuf_O),	// @[Harness.scala:81:26, :86:22]
//    .clk_out1 (_harnessSysPLL_clk_out1),
//    .locked   (_harnessSysPLL_locked)
//  );
//  IBUFG sys_clock_ibufg (	// @[ClockOverlay.scala:32:22]
//    .I (sys_clock),
//    .O (_sys_clock_ibufg_O)
//  );

  // System
  assign _reset_ibuf_O = reset;
  assign _dutGroup_auto_out_reset = ~_reset_ibuf_O;
  assign _harnessSysPLL_clk_out1 = sys_clock;
  assign _dutGroup_auto_out_clock = _harnessSysPLL_clk_out1;
  
  // JTAG
  assign _bundleIn_0_TCK_a2b_b = jtag_jtag_TCK;
  assign _bundleIn_0_TMS_a2b_b = jtag_jtag_TMS;
  assign _bundleIn_0_TDI_a2b_b = jtag_jtag_TDI;
  
  assign jtag_jtag_TDO          = _chiptop0_jtag_TDO;
//  AnalogToUInt_1 bundleIn_0_TCK_a2b (	// @[Util.scala:30:21]
//    .a (jtag_jtag_TCK),
//    .b (_bundleIn_0_TCK_a2b_b)
//  );
//  AnalogToUInt_1 bundleIn_0_TMS_a2b (	// @[Util.scala:30:21]
//    .a (jtag_jtag_TMS),
//    .b (_bundleIn_0_TMS_a2b_b)
//  );
//  AnalogToUInt_1 bundleIn_0_TDI_a2b (	// @[Util.scala:30:21]
//    .a (jtag_jtag_TDI),
//    .b (_bundleIn_0_TDI_a2b_b)
//  );
//  UIntToAnalog_1 a2b (	// @[Util.scala:58:21]
//    .a    (jtag_jtag_TDO),
//    .b    (_chiptop0_jtag_TDO),	// @[HasHarnessInstantiators.scala:82:40]
//    .b_en (1'h1)	// @[Util.scala:61:17]
//  );
  
  // UART
  assign uart_txd = _chiptop0_uart_0_txd;
  assign _bundleIn_0_rxd_a2b_b = uart_rxd;
  
  assign uart2_txd = _chiptop0_uart_1_txd;
  assign _bundleIn_0_rxd_a2b_1_b = uart2_rxd;
  
//  UIntToAnalog_1 a2b_1 (	// @[Util.scala:58:21]
//    .a    (uart_txd),
//    .b    (_chiptop0_uart_0_txd),	// @[HasHarnessInstantiators.scala:82:40]
//    .b_en (1'h1)	// @[Util.scala:61:17]
//  );
//  AnalogToUInt_1 bundleIn_0_rxd_a2b (	// @[Util.scala:30:21]
//    .a (uart_rxd),
//    .b (_bundleIn_0_rxd_a2b_b)
//  );
//  UIntToAnalog_1 a2b_2 (	// @[Util.scala:58:21]
//    .a    (uart2_txd),
//    .b    (_chiptop0_uart_1_txd),	// @[HasHarnessInstantiators.scala:82:40]
//    .b_en (1'h1)	// @[Util.scala:61:17]
//  );
//  AnalogToUInt_1 bundleIn_0_rxd_a2b_1 (	// @[Util.scala:30:21]
//    .a (uart2_rxd),
//    .b (_bundleIn_0_rxd_a2b_1_b)
//  );
  
  // GPIO
  UIntToAnalog_1 a2b_3 (	// @[Util.scala:58:21]
    .a    (gpio_gpio_0),
    .b    (_chiptop0_gpio_0_pins_0_o_oval),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_gpio_0_pins_0_o_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_pins_0_i_ival_a2b (	// @[Util.scala:30:21]
    .a (gpio_gpio_0),
    .b (_bundleIn_0_pins_0_i_ival_a2b_b)
  );
  UIntToAnalog_1 a2b_4 (	// @[Util.scala:58:21]
    .a    (gpio_gpio_1),
    .b    (_chiptop0_gpio_0_pins_1_o_oval),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_gpio_0_pins_1_o_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_pins_1_i_ival_a2b (	// @[Util.scala:30:21]
    .a (gpio_gpio_1),
    .b (_bundleIn_0_pins_1_i_ival_a2b_b)
  );
  UIntToAnalog_1 a2b_5 (	// @[Util.scala:58:21]
    .a    (gpio_gpio_2),
    .b    (_chiptop0_gpio_0_pins_2_o_oval),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_gpio_0_pins_2_o_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_pins_2_i_ival_a2b (	// @[Util.scala:30:21]
    .a (gpio_gpio_2),
    .b (_bundleIn_0_pins_2_i_ival_a2b_b)
  );
  UIntToAnalog_1 a2b_6 (	// @[Util.scala:58:21]
    .a    (gpio_gpio_3),
    .b    (_chiptop0_gpio_0_pins_3_o_oval),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_gpio_0_pins_3_o_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_pins_3_i_ival_a2b (	// @[Util.scala:30:21]
    .a (gpio_gpio_3),
    .b (_bundleIn_0_pins_3_i_ival_a2b_b)
  );
  UIntToAnalog_1 a2b_7 (	// @[Util.scala:58:21]
    .a    (gpio_gpio_4),
    .b    (_chiptop0_gpio_0_pins_4_o_oval),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_gpio_0_pins_4_o_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_pins_4_i_ival_a2b (	// @[Util.scala:30:21]
    .a (gpio_gpio_4),
    .b (_bundleIn_0_pins_4_i_ival_a2b_b)
  );
  UIntToAnalog_1 a2b_8 (	// @[Util.scala:58:21]
    .a    (gpio_gpio_5),
    .b    (_chiptop0_gpio_0_pins_5_o_oval),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_gpio_0_pins_5_o_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_pins_5_i_ival_a2b (	// @[Util.scala:30:21]
    .a (gpio_gpio_5),
    .b (_bundleIn_0_pins_5_i_ival_a2b_b)
  );
  UIntToAnalog_1 a2b_9 (	// @[Util.scala:58:21]
    .a    (gpio_gpio_6),
    .b    (_chiptop0_gpio_0_pins_6_o_oval),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_gpio_0_pins_6_o_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_pins_6_i_ival_a2b (	// @[Util.scala:30:21]
    .a (gpio_gpio_6),
    .b (_bundleIn_0_pins_6_i_ival_a2b_b)
  );
  UIntToAnalog_1 a2b_10 (	// @[Util.scala:58:21]
    .a    (gpio_gpio_7),
    .b    (_chiptop0_gpio_0_pins_7_o_oval),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_gpio_0_pins_7_o_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_pins_7_i_ival_a2b (	// @[Util.scala:30:21]
    .a (gpio_gpio_7),
    .b (_bundleIn_0_pins_7_i_ival_a2b_b)
  );
  UIntToAnalog_1 a2b_11 (	// @[Util.scala:58:21]
    .a    (sdio_spi_clk),
    .b    (_chiptop0_spi_0_sck),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  UIntToAnalog_1 a2b_12 (	// @[Util.scala:58:21]
    .a    (sdio_spi_dat_3),
    .b    (_chiptop0_spi_0_cs_0),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  UIntToAnalog_1 a2b_13 (	// @[Util.scala:58:21]
    .a    (sdio_spi_cs),
    .b    (_chiptop0_spi_0_dq_0_o),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  AnalogToUInt_1 a2b_14 (	// @[Util.scala:30:21]
    .a (sdio_spi_dat_0),
    .b (_a2b_14_b)
  );
  UIntToAnalog_1 a2b_15 (	// @[Util.scala:58:21]
    .a    (flash_qspi_sck),
    .b    (_chiptop0_qspi_0_sck),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  UIntToAnalog_1 a2b_16 (	// @[Util.scala:58:21]
    .a    (flash_qspi_cs),
    .b    (_chiptop0_qspi_0_cs_0),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (1'h1)	// @[Util.scala:61:17]
  );
  UIntToAnalog_1 a2b_17 (	// @[Util.scala:58:21]
    .a    (flash_qspi_dq_0),
    .b    (_chiptop0_qspi_0_dq_0_o),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_qspi_0_dq_0_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_dq_0_i_a2b (	// @[Util.scala:30:21]
    .a (flash_qspi_dq_0),
    .b (_bundleIn_0_dq_0_i_a2b_b)
  );
  UIntToAnalog_1 a2b_18 (	// @[Util.scala:58:21]
    .a    (flash_qspi_dq_1),
    .b    (_chiptop0_qspi_0_dq_1_o),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_qspi_0_dq_1_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_dq_1_i_a2b (	// @[Util.scala:30:21]
    .a (flash_qspi_dq_1),
    .b (_bundleIn_0_dq_1_i_a2b_b)
  );
  UIntToAnalog_1 a2b_19 (	// @[Util.scala:58:21]
    .a    (flash_qspi_dq_2),
    .b    (_chiptop0_qspi_0_dq_2_o),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_qspi_0_dq_2_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_dq_2_i_a2b (	// @[Util.scala:30:21]
    .a (flash_qspi_dq_2),
    .b (_bundleIn_0_dq_2_i_a2b_b)
  );
  UIntToAnalog_1 a2b_20 (	// @[Util.scala:58:21]
    .a    (flash_qspi_dq_3),
    .b    (_chiptop0_qspi_0_dq_3_o),	// @[HasHarnessInstantiators.scala:82:40]
    .b_en (_chiptop0_qspi_0_dq_3_oe)	// @[HasHarnessInstantiators.scala:82:40]
  );
  AnalogToUInt_1 bundleIn_0_dq_3_i_a2b (	// @[Util.scala:30:21]
    .a (flash_qspi_dq_3),
    .b (_bundleIn_0_dq_3_i_a2b_b)
  );
//  IBUF reset_ibuf (	// @[Harness.scala:81:26]
//    .I (reset),
//    .O (_reset_ibuf_O)
//  );
  ChipTop chiptop0 (	// @[HasHarnessInstantiators.scala:82:40]
    .serial_tl_clock          (_dutWrangler_auto_out_clock),	// @[Harness.scala:31:31]
    .serial_tl_bits_in_valid  (_ram_io_ser_in_valid),	// @[TSIHarness.scala:24:24]
    .serial_tl_bits_in_bits   (_ram_io_ser_in_bits),	// @[TSIHarness.scala:24:24]
    .serial_tl_bits_out_ready (_ram_io_ser_out_ready),	// @[TSIHarness.scala:24:24]
    .reset_io                 (_harnessBinderReset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .clock_uncore_clock       (_dutWrangler_auto_out_clock),	// @[Harness.scala:31:31]
    .jtag_TCK                 (_bundleIn_0_TCK_a2b_b),	// @[Util.scala:30:21]
    .jtag_TMS                 (_bundleIn_0_TMS_a2b_b),	// @[Util.scala:30:21]
    .jtag_TDI                 (_bundleIn_0_TDI_a2b_b),	// @[Util.scala:30:21]
    .spi_0_dq_0_i             (1'h0),	// @[LazyModule.scala:411:29]
    .spi_0_dq_1_i             (bundleIn_0_dq_1_i_REG_1),	// @[SDIOOverlay.scala:19:31]
    .spi_0_dq_2_i             (1'h0),	// @[LazyModule.scala:411:29]
    .spi_0_dq_3_i             (1'h0),	// @[LazyModule.scala:411:29]
    .uart_0_rxd               (_bundleIn_0_rxd_a2b_b),	// @[Util.scala:30:21]
    .uart_1_rxd               (_bundleIn_0_rxd_a2b_1_b),	// @[Util.scala:30:21]
    .gpio_0_pins_0_i_ival     (_bundleIn_0_pins_0_i_ival_a2b_b),	// @[Util.scala:30:21]
    .gpio_0_pins_0_i_po       (1'h0),	// @[LazyModule.scala:411:29]
    .gpio_0_pins_1_i_ival     (_bundleIn_0_pins_1_i_ival_a2b_b),	// @[Util.scala:30:21]
    .gpio_0_pins_1_i_po       (1'h0),	// @[LazyModule.scala:411:29]
    .gpio_0_pins_2_i_ival     (_bundleIn_0_pins_2_i_ival_a2b_b),	// @[Util.scala:30:21]
    .gpio_0_pins_2_i_po       (1'h0),	// @[LazyModule.scala:411:29]
    .gpio_0_pins_3_i_ival     (_bundleIn_0_pins_3_i_ival_a2b_b),	// @[Util.scala:30:21]
    .gpio_0_pins_3_i_po       (1'h0),	// @[LazyModule.scala:411:29]
    .gpio_0_pins_4_i_ival     (_bundleIn_0_pins_4_i_ival_a2b_b),	// @[Util.scala:30:21]
    .gpio_0_pins_4_i_po       (1'h0),	// @[LazyModule.scala:411:29]
    .gpio_0_pins_5_i_ival     (_bundleIn_0_pins_5_i_ival_a2b_b),	// @[Util.scala:30:21]
    .gpio_0_pins_5_i_po       (1'h0),	// @[LazyModule.scala:411:29]
    .gpio_0_pins_6_i_ival     (_bundleIn_0_pins_6_i_ival_a2b_b),	// @[Util.scala:30:21]
    .gpio_0_pins_6_i_po       (1'h0),	// @[LazyModule.scala:411:29]
    .gpio_0_pins_7_i_ival     (_bundleIn_0_pins_7_i_ival_a2b_b),	// @[Util.scala:30:21]
    .gpio_0_pins_7_i_po       (1'h0),	// @[LazyModule.scala:411:29]
    .qspi_0_dq_0_i            (_bundleIn_0_dq_0_i_a2b_b),	// @[Util.scala:30:21]
    .qspi_0_dq_1_i            (_bundleIn_0_dq_1_i_a2b_b),	// @[Util.scala:30:21]
    .qspi_0_dq_2_i            (_bundleIn_0_dq_2_i_a2b_b),	// @[Util.scala:30:21]
    .qspi_0_dq_3_i            (_bundleIn_0_dq_3_i_a2b_b),	// @[Util.scala:30:21]
    .serial_tl_bits_in_ready  (_chiptop0_serial_tl_bits_in_ready),
    .serial_tl_bits_out_valid (_chiptop0_serial_tl_bits_out_valid),
    .serial_tl_bits_out_bits  (_chiptop0_serial_tl_bits_out_bits),
    .jtag_TDO                 (_chiptop0_jtag_TDO),
    .spi_0_sck                (_chiptop0_spi_0_sck),
    .spi_0_dq_0_o             (_chiptop0_spi_0_dq_0_o),
    .spi_0_dq_0_ie            (_chiptop0_spi_0_dq_0_ie),
    .spi_0_dq_0_oe            (_chiptop0_spi_0_dq_0_oe),
    .spi_0_dq_1_o             (_chiptop0_spi_0_dq_1_o),
    .spi_0_dq_1_ie            (_chiptop0_spi_0_dq_1_ie),
    .spi_0_dq_1_oe            (_chiptop0_spi_0_dq_1_oe),
    .spi_0_dq_2_o             (_chiptop0_spi_0_dq_2_o),
    .spi_0_dq_2_ie            (_chiptop0_spi_0_dq_2_ie),
    .spi_0_dq_2_oe            (_chiptop0_spi_0_dq_2_oe),
    .spi_0_dq_3_o             (_chiptop0_spi_0_dq_3_o),
    .spi_0_dq_3_ie            (_chiptop0_spi_0_dq_3_ie),
    .spi_0_dq_3_oe            (_chiptop0_spi_0_dq_3_oe),
    .spi_0_cs_0               (_chiptop0_spi_0_cs_0),
    .uart_0_txd               (_chiptop0_uart_0_txd),
    .uart_1_txd               (_chiptop0_uart_1_txd),
    .gpio_0_pins_0_o_oval     (_chiptop0_gpio_0_pins_0_o_oval),
    .gpio_0_pins_0_o_oe       (_chiptop0_gpio_0_pins_0_o_oe),
    .gpio_0_pins_0_o_ie       (_chiptop0_gpio_0_pins_0_o_ie),
    .gpio_0_pins_0_o_pue      (_chiptop0_gpio_0_pins_0_o_pue),
    .gpio_0_pins_0_o_ds       (_chiptop0_gpio_0_pins_0_o_ds),
    .gpio_0_pins_0_o_ps       (_chiptop0_gpio_0_pins_0_o_ps),
    .gpio_0_pins_0_o_ds1      (_chiptop0_gpio_0_pins_0_o_ds1),
    .gpio_0_pins_0_o_poe      (_chiptop0_gpio_0_pins_0_o_poe),
    .gpio_0_pins_1_o_oval     (_chiptop0_gpio_0_pins_1_o_oval),
    .gpio_0_pins_1_o_oe       (_chiptop0_gpio_0_pins_1_o_oe),
    .gpio_0_pins_1_o_ie       (_chiptop0_gpio_0_pins_1_o_ie),
    .gpio_0_pins_1_o_pue      (_chiptop0_gpio_0_pins_1_o_pue),
    .gpio_0_pins_1_o_ds       (_chiptop0_gpio_0_pins_1_o_ds),
    .gpio_0_pins_1_o_ps       (_chiptop0_gpio_0_pins_1_o_ps),
    .gpio_0_pins_1_o_ds1      (_chiptop0_gpio_0_pins_1_o_ds1),
    .gpio_0_pins_1_o_poe      (_chiptop0_gpio_0_pins_1_o_poe),
    .gpio_0_pins_2_o_oval     (_chiptop0_gpio_0_pins_2_o_oval),
    .gpio_0_pins_2_o_oe       (_chiptop0_gpio_0_pins_2_o_oe),
    .gpio_0_pins_2_o_ie       (_chiptop0_gpio_0_pins_2_o_ie),
    .gpio_0_pins_2_o_pue      (_chiptop0_gpio_0_pins_2_o_pue),
    .gpio_0_pins_2_o_ds       (_chiptop0_gpio_0_pins_2_o_ds),
    .gpio_0_pins_2_o_ps       (_chiptop0_gpio_0_pins_2_o_ps),
    .gpio_0_pins_2_o_ds1      (_chiptop0_gpio_0_pins_2_o_ds1),
    .gpio_0_pins_2_o_poe      (_chiptop0_gpio_0_pins_2_o_poe),
    .gpio_0_pins_3_o_oval     (_chiptop0_gpio_0_pins_3_o_oval),
    .gpio_0_pins_3_o_oe       (_chiptop0_gpio_0_pins_3_o_oe),
    .gpio_0_pins_3_o_ie       (_chiptop0_gpio_0_pins_3_o_ie),
    .gpio_0_pins_3_o_pue      (_chiptop0_gpio_0_pins_3_o_pue),
    .gpio_0_pins_3_o_ds       (_chiptop0_gpio_0_pins_3_o_ds),
    .gpio_0_pins_3_o_ps       (_chiptop0_gpio_0_pins_3_o_ps),
    .gpio_0_pins_3_o_ds1      (_chiptop0_gpio_0_pins_3_o_ds1),
    .gpio_0_pins_3_o_poe      (_chiptop0_gpio_0_pins_3_o_poe),
    .gpio_0_pins_4_o_oval     (_chiptop0_gpio_0_pins_4_o_oval),
    .gpio_0_pins_4_o_oe       (_chiptop0_gpio_0_pins_4_o_oe),
    .gpio_0_pins_4_o_ie       (_chiptop0_gpio_0_pins_4_o_ie),
    .gpio_0_pins_4_o_pue      (_chiptop0_gpio_0_pins_4_o_pue),
    .gpio_0_pins_4_o_ds       (_chiptop0_gpio_0_pins_4_o_ds),
    .gpio_0_pins_4_o_ps       (_chiptop0_gpio_0_pins_4_o_ps),
    .gpio_0_pins_4_o_ds1      (_chiptop0_gpio_0_pins_4_o_ds1),
    .gpio_0_pins_4_o_poe      (_chiptop0_gpio_0_pins_4_o_poe),
    .gpio_0_pins_5_o_oval     (_chiptop0_gpio_0_pins_5_o_oval),
    .gpio_0_pins_5_o_oe       (_chiptop0_gpio_0_pins_5_o_oe),
    .gpio_0_pins_5_o_ie       (_chiptop0_gpio_0_pins_5_o_ie),
    .gpio_0_pins_5_o_pue      (_chiptop0_gpio_0_pins_5_o_pue),
    .gpio_0_pins_5_o_ds       (_chiptop0_gpio_0_pins_5_o_ds),
    .gpio_0_pins_5_o_ps       (_chiptop0_gpio_0_pins_5_o_ps),
    .gpio_0_pins_5_o_ds1      (_chiptop0_gpio_0_pins_5_o_ds1),
    .gpio_0_pins_5_o_poe      (_chiptop0_gpio_0_pins_5_o_poe),
    .gpio_0_pins_6_o_oval     (_chiptop0_gpio_0_pins_6_o_oval),
    .gpio_0_pins_6_o_oe       (_chiptop0_gpio_0_pins_6_o_oe),
    .gpio_0_pins_6_o_ie       (_chiptop0_gpio_0_pins_6_o_ie),
    .gpio_0_pins_6_o_pue      (_chiptop0_gpio_0_pins_6_o_pue),
    .gpio_0_pins_6_o_ds       (_chiptop0_gpio_0_pins_6_o_ds),
    .gpio_0_pins_6_o_ps       (_chiptop0_gpio_0_pins_6_o_ps),
    .gpio_0_pins_6_o_ds1      (_chiptop0_gpio_0_pins_6_o_ds1),
    .gpio_0_pins_6_o_poe      (_chiptop0_gpio_0_pins_6_o_poe),
    .gpio_0_pins_7_o_oval     (_chiptop0_gpio_0_pins_7_o_oval),
    .gpio_0_pins_7_o_oe       (_chiptop0_gpio_0_pins_7_o_oe),
    .gpio_0_pins_7_o_ie       (_chiptop0_gpio_0_pins_7_o_ie),
    .gpio_0_pins_7_o_pue      (_chiptop0_gpio_0_pins_7_o_pue),
    .gpio_0_pins_7_o_ds       (_chiptop0_gpio_0_pins_7_o_ds),
    .gpio_0_pins_7_o_ps       (_chiptop0_gpio_0_pins_7_o_ps),
    .gpio_0_pins_7_o_ds1      (_chiptop0_gpio_0_pins_7_o_ds1),
    .gpio_0_pins_7_o_poe      (_chiptop0_gpio_0_pins_7_o_poe),
    .qspi_0_sck               (_chiptop0_qspi_0_sck),
    .qspi_0_dq_0_o            (_chiptop0_qspi_0_dq_0_o),
    .qspi_0_dq_0_ie           (_chiptop0_qspi_0_dq_0_ie),
    .qspi_0_dq_0_oe           (_chiptop0_qspi_0_dq_0_oe),
    .qspi_0_dq_1_o            (_chiptop0_qspi_0_dq_1_o),
    .qspi_0_dq_1_ie           (_chiptop0_qspi_0_dq_1_ie),
    .qspi_0_dq_1_oe           (_chiptop0_qspi_0_dq_1_oe),
    .qspi_0_dq_2_o            (_chiptop0_qspi_0_dq_2_o),
    .qspi_0_dq_2_ie           (_chiptop0_qspi_0_dq_2_ie),
    .qspi_0_dq_2_oe           (_chiptop0_qspi_0_dq_2_oe),
    .qspi_0_dq_3_o            (_chiptop0_qspi_0_dq_3_o),
    .qspi_0_dq_3_ie           (_chiptop0_qspi_0_dq_3_ie),
    .qspi_0_dq_3_oe           (_chiptop0_qspi_0_dq_3_oe),
    .qspi_0_cs_0              (_chiptop0_qspi_0_cs_0)
  );
  SerialRAM ram (	// @[TSIHarness.scala:24:24]
    .clock            (_dutWrangler_auto_out_clock),	// @[Harness.scala:31:31]
    .reset            (_harnessBinderReset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .io_ser_in_ready  (_chiptop0_serial_tl_bits_in_ready),	// @[HasHarnessInstantiators.scala:82:40]
    .io_ser_out_valid (_chiptop0_serial_tl_bits_out_valid),	// @[HasHarnessInstantiators.scala:82:40]
    .io_ser_out_bits  (_chiptop0_serial_tl_bits_out_bits),	// @[HasHarnessInstantiators.scala:82:40]
    .io_ser_in_valid  (_ram_io_ser_in_valid),
    .io_ser_in_bits   (_ram_io_ser_in_bits),
    .io_ser_out_ready (_ram_io_ser_out_ready)
  );
  ResetCatchAndSync_d3_Arty100TDDRHarness_UNIQUIFIED harnessBinderReset_catcher (	// @[ResetCatchAndSync.scala:39:28]
    .clock         (_dutWrangler_auto_out_clock),	// @[Harness.scala:31:31]
    .reset         (_dutWrangler_auto_out_reset),	// @[Harness.scala:31:31]
    .io_sync_reset (_harnessBinderReset_catcher_io_sync_reset)
  );
endmodule

