// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module ChipTop(
  input        serial_tl_clock,
               serial_tl_bits_in_valid,
  input  [3:0] serial_tl_bits_in_bits,
  input        serial_tl_bits_out_ready,
               reset_io,
               clock_uncore_clock,
               jtag_TCK,
               jtag_TMS,
               jtag_TDI,
               spi_0_dq_0_i,
               spi_0_dq_1_i,
               spi_0_dq_2_i,
               spi_0_dq_3_i,
               uart_0_rxd,
               uart_1_rxd,
               gpio_0_pins_0_i_ival,
               gpio_0_pins_0_i_po,
               gpio_0_pins_1_i_ival,
               gpio_0_pins_1_i_po,
               gpio_0_pins_2_i_ival,
               gpio_0_pins_2_i_po,
               gpio_0_pins_3_i_ival,
               gpio_0_pins_3_i_po,
               gpio_0_pins_4_i_ival,
               gpio_0_pins_4_i_po,
               gpio_0_pins_5_i_ival,
               gpio_0_pins_5_i_po,
               gpio_0_pins_6_i_ival,
               gpio_0_pins_6_i_po,
               gpio_0_pins_7_i_ival,
               gpio_0_pins_7_i_po,
               qspi_0_dq_0_i,
               qspi_0_dq_1_i,
               qspi_0_dq_2_i,
               qspi_0_dq_3_i,
  output       serial_tl_bits_in_ready,
               serial_tl_bits_out_valid,
  output [3:0] serial_tl_bits_out_bits,
  output       jtag_TDO,
               spi_0_sck,
               spi_0_dq_0_o,
               spi_0_dq_0_ie,
               spi_0_dq_0_oe,
               spi_0_dq_1_o,
               spi_0_dq_1_ie,
               spi_0_dq_1_oe,
               spi_0_dq_2_o,
               spi_0_dq_2_ie,
               spi_0_dq_2_oe,
               spi_0_dq_3_o,
               spi_0_dq_3_ie,
               spi_0_dq_3_oe,
               spi_0_cs_0,
               uart_0_txd,
               uart_1_txd,
               gpio_0_pins_0_o_oval,
               gpio_0_pins_0_o_oe,
               gpio_0_pins_0_o_ie,
               gpio_0_pins_0_o_pue,
               gpio_0_pins_0_o_ds,
               gpio_0_pins_0_o_ps,
               gpio_0_pins_0_o_ds1,
               gpio_0_pins_0_o_poe,
               gpio_0_pins_1_o_oval,
               gpio_0_pins_1_o_oe,
               gpio_0_pins_1_o_ie,
               gpio_0_pins_1_o_pue,
               gpio_0_pins_1_o_ds,
               gpio_0_pins_1_o_ps,
               gpio_0_pins_1_o_ds1,
               gpio_0_pins_1_o_poe,
               gpio_0_pins_2_o_oval,
               gpio_0_pins_2_o_oe,
               gpio_0_pins_2_o_ie,
               gpio_0_pins_2_o_pue,
               gpio_0_pins_2_o_ds,
               gpio_0_pins_2_o_ps,
               gpio_0_pins_2_o_ds1,
               gpio_0_pins_2_o_poe,
               gpio_0_pins_3_o_oval,
               gpio_0_pins_3_o_oe,
               gpio_0_pins_3_o_ie,
               gpio_0_pins_3_o_pue,
               gpio_0_pins_3_o_ds,
               gpio_0_pins_3_o_ps,
               gpio_0_pins_3_o_ds1,
               gpio_0_pins_3_o_poe,
               gpio_0_pins_4_o_oval,
               gpio_0_pins_4_o_oe,
               gpio_0_pins_4_o_ie,
               gpio_0_pins_4_o_pue,
               gpio_0_pins_4_o_ds,
               gpio_0_pins_4_o_ps,
               gpio_0_pins_4_o_ds1,
               gpio_0_pins_4_o_poe,
               gpio_0_pins_5_o_oval,
               gpio_0_pins_5_o_oe,
               gpio_0_pins_5_o_ie,
               gpio_0_pins_5_o_pue,
               gpio_0_pins_5_o_ds,
               gpio_0_pins_5_o_ps,
               gpio_0_pins_5_o_ds1,
               gpio_0_pins_5_o_poe,
               gpio_0_pins_6_o_oval,
               gpio_0_pins_6_o_oe,
               gpio_0_pins_6_o_ie,
               gpio_0_pins_6_o_pue,
               gpio_0_pins_6_o_ds,
               gpio_0_pins_6_o_ps,
               gpio_0_pins_6_o_ds1,
               gpio_0_pins_6_o_poe,
               gpio_0_pins_7_o_oval,
               gpio_0_pins_7_o_oe,
               gpio_0_pins_7_o_ie,
               gpio_0_pins_7_o_pue,
               gpio_0_pins_7_o_ds,
               gpio_0_pins_7_o_ps,
               gpio_0_pins_7_o_ds1,
               gpio_0_pins_7_o_poe,
               qspi_0_sck,
               qspi_0_dq_0_o,
               qspi_0_dq_0_ie,
               qspi_0_dq_0_oe,
               qspi_0_dq_1_o,
               qspi_0_dq_1_ie,
               qspi_0_dq_1_oe,
               qspi_0_dq_2_o,
               qspi_0_dq_2_ie,
               qspi_0_dq_2_oe,
               qspi_0_dq_3_o,
               qspi_0_dq_3_ie,
               qspi_0_dq_3_oe,
               qspi_0_cs_0
);

  wire       _iocell_jtag_TCK_i;	// @[IOCell.scala:111:23]
  wire       _iocell_jtag_TMS_i;	// @[IOCell.scala:111:23]
  wire       _iocell_jtag_TDI_i;	// @[IOCell.scala:111:23]
  wire       _dmactiveAck_dmactiveAck_io_q;	// @[ShiftReg.scala:45:23]
  wire       _debug_reset_syncd_debug_reset_sync_io_q;	// @[ShiftReg.scala:45:23]
  wire       _system_debug_systemjtag_reset_catcher_io_sync_reset;	// @[ResetCatchAndSync.scala:39:28]
  wire       _iocell_serial_tl_clock_i;	// @[IOCell.scala:111:23]
  wire       _iocell_serial_tl_bits_in_valid_i;	// @[IOCell.scala:111:23]
  wire       _iocell_serial_tl_bits_in_bits_3_i;	// @[IOCell.scala:111:23]
  wire       _iocell_serial_tl_bits_in_bits_2_i;	// @[IOCell.scala:111:23]
  wire       _iocell_serial_tl_bits_in_bits_1_i;	// @[IOCell.scala:111:23]
  wire       _iocell_serial_tl_bits_in_bits_i;	// @[IOCell.scala:111:23]
  wire       _iocell_serial_tl_bits_out_ready_i;	// @[IOCell.scala:111:23]
  wire       _iocell_serial_tl_bits_out_bits_3_pad;	// @[IOCell.scala:112:24]
  wire       _iocell_serial_tl_bits_out_bits_2_pad;	// @[IOCell.scala:112:24]
  wire       _iocell_serial_tl_bits_out_bits_1_pad;	// @[IOCell.scala:112:24]
  wire       _iocell_serial_tl_bits_out_bits_pad;	// @[IOCell.scala:112:24]
  wire       _system_auto_implicitClockGrouper_out_clock;	// @[ChipTop.scala:28:35]
  wire       _system_auto_implicitClockGrouper_out_reset;	// @[ChipTop.scala:28:35]
  wire       _system_auto_subsystem_cbus_fixedClockNode_out_clock;	// @[ChipTop.scala:28:35]
  wire       _system_auto_subsystem_cbus_fixedClockNode_out_reset;	// @[ChipTop.scala:28:35]
  wire       _system_debug_systemjtag_jtag_TDO_data;	// @[ChipTop.scala:28:35]
  wire       _system_debug_dmactive;	// @[ChipTop.scala:28:35]
  wire       _system_serial_tl_bits_in_ready;	// @[ChipTop.scala:28:35]
  wire       _system_serial_tl_bits_out_valid;	// @[ChipTop.scala:28:35]
  wire [3:0] _system_serial_tl_bits_out_bits;	// @[ChipTop.scala:28:35]
  DigitalTop system (	// @[ChipTop.scala:28:35]
    .clock                                                                     (_system_auto_implicitClockGrouper_out_clock),	// @[ChipTop.scala:28:35]
    .reset                                                                     (_system_auto_implicitClockGrouper_out_reset),	// @[ChipTop.scala:28:35]
    .auto_prci_ctrl_domain_reset_setter_clock_in_member_allClocks_uncore_clock (clock_uncore_clock),
    .auto_prci_ctrl_domain_reset_setter_clock_in_member_allClocks_uncore_reset (reset_io),
    .resetctrl_hartIsInReset_0                                                 (_system_auto_subsystem_cbus_fixedClockNode_out_reset),	// @[ChipTop.scala:28:35]
    .debug_clock                                                               (_system_auto_subsystem_cbus_fixedClockNode_out_clock),	// @[ChipTop.scala:28:35]
    .debug_reset                                                               (~_debug_reset_syncd_debug_reset_sync_io_q),	// @[Periphery.scala:287:40, ShiftReg.scala:45:23]
    .debug_systemjtag_jtag_TCK                                                 (_iocell_jtag_TCK_i),	// @[IOCell.scala:111:23]
    .debug_systemjtag_jtag_TMS                                                 (_iocell_jtag_TMS_i),	// @[IOCell.scala:111:23]
    .debug_systemjtag_jtag_TDI                                                 (_iocell_jtag_TDI_i),	// @[IOCell.scala:111:23]
    .debug_systemjtag_reset                                                    (_system_debug_systemjtag_reset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .debug_dmactiveAck                                                         (_dmactiveAck_dmactiveAck_io_q),	// @[ShiftReg.scala:45:23]
    .serial_tl_clock                                                           (_iocell_serial_tl_clock_i),	// @[IOCell.scala:111:23]
    .serial_tl_bits_in_valid                                                   (_iocell_serial_tl_bits_in_valid_i),	// @[IOCell.scala:111:23]
    .serial_tl_bits_in_bits                                                    ({_iocell_serial_tl_bits_in_bits_3_i, _iocell_serial_tl_bits_in_bits_2_i, _iocell_serial_tl_bits_in_bits_1_i, _iocell_serial_tl_bits_in_bits_i}),	// @[Cat.scala:33:92, IOCell.scala:111:23]
    .serial_tl_bits_out_ready                                                  (_iocell_serial_tl_bits_out_ready_i),	// @[IOCell.scala:111:23]
    .uart_0_rxd                                                                (uart_0_rxd),
    .uart_1_rxd                                                                (uart_1_rxd),
    .gpio_0_pins_0_i_ival                                                      (gpio_0_pins_0_i_ival),
    .gpio_0_pins_1_i_ival                                                      (gpio_0_pins_1_i_ival),
    .gpio_0_pins_2_i_ival                                                      (gpio_0_pins_2_i_ival),
    .gpio_0_pins_3_i_ival                                                      (gpio_0_pins_3_i_ival),
    .gpio_0_pins_4_i_ival                                                      (gpio_0_pins_4_i_ival),
    .gpio_0_pins_5_i_ival                                                      (gpio_0_pins_5_i_ival),
    .gpio_0_pins_6_i_ival                                                      (gpio_0_pins_6_i_ival),
    .gpio_0_pins_7_i_ival                                                      (gpio_0_pins_7_i_ival),
    .qspi_0_dq_0_i                                                             (qspi_0_dq_0_i),
    .qspi_0_dq_1_i                                                             (qspi_0_dq_1_i),
    .qspi_0_dq_2_i                                                             (qspi_0_dq_2_i),
    .qspi_0_dq_3_i                                                             (qspi_0_dq_3_i),
    .spi_0_dq_0_i                                                              (spi_0_dq_0_i),
    .spi_0_dq_1_i                                                              (spi_0_dq_1_i),
    .spi_0_dq_2_i                                                              (spi_0_dq_2_i),
    .spi_0_dq_3_i                                                              (spi_0_dq_3_i),
    .auto_implicitClockGrouper_out_clock                                       (_system_auto_implicitClockGrouper_out_clock),
    .auto_implicitClockGrouper_out_reset                                       (_system_auto_implicitClockGrouper_out_reset),
    .auto_subsystem_cbus_fixedClockNode_out_clock                              (_system_auto_subsystem_cbus_fixedClockNode_out_clock),
    .auto_subsystem_cbus_fixedClockNode_out_reset                              (_system_auto_subsystem_cbus_fixedClockNode_out_reset),
    .debug_systemjtag_jtag_TDO_data                                            (_system_debug_systemjtag_jtag_TDO_data),
    .debug_dmactive                                                            (_system_debug_dmactive),
    .serial_tl_bits_in_ready                                                   (_system_serial_tl_bits_in_ready),
    .serial_tl_bits_out_valid                                                  (_system_serial_tl_bits_out_valid),
    .serial_tl_bits_out_bits                                                   (_system_serial_tl_bits_out_bits),
    .uart_0_txd                                                                (uart_0_txd),
    .uart_1_txd                                                                (uart_1_txd),
    .gpio_0_pins_0_o_oval                                                      (gpio_0_pins_0_o_oval),
    .gpio_0_pins_0_o_oe                                                        (gpio_0_pins_0_o_oe),
    .gpio_0_pins_0_o_ie                                                        (gpio_0_pins_0_o_ie),
    .gpio_0_pins_0_o_pue                                                       (gpio_0_pins_0_o_pue),
    .gpio_0_pins_0_o_ds                                                        (gpio_0_pins_0_o_ds),
    .gpio_0_pins_0_o_ds1                                                       (gpio_0_pins_0_o_ds1),
    .gpio_0_pins_0_o_poe                                                       (gpio_0_pins_0_o_poe),
    .gpio_0_pins_1_o_oval                                                      (gpio_0_pins_1_o_oval),
    .gpio_0_pins_1_o_oe                                                        (gpio_0_pins_1_o_oe),
    .gpio_0_pins_1_o_ie                                                        (gpio_0_pins_1_o_ie),
    .gpio_0_pins_1_o_pue                                                       (gpio_0_pins_1_o_pue),
    .gpio_0_pins_1_o_ds                                                        (gpio_0_pins_1_o_ds),
    .gpio_0_pins_1_o_ds1                                                       (gpio_0_pins_1_o_ds1),
    .gpio_0_pins_1_o_poe                                                       (gpio_0_pins_1_o_poe),
    .gpio_0_pins_2_o_oval                                                      (gpio_0_pins_2_o_oval),
    .gpio_0_pins_2_o_oe                                                        (gpio_0_pins_2_o_oe),
    .gpio_0_pins_2_o_ie                                                        (gpio_0_pins_2_o_ie),
    .gpio_0_pins_2_o_pue                                                       (gpio_0_pins_2_o_pue),
    .gpio_0_pins_2_o_ds                                                        (gpio_0_pins_2_o_ds),
    .gpio_0_pins_2_o_ds1                                                       (gpio_0_pins_2_o_ds1),
    .gpio_0_pins_2_o_poe                                                       (gpio_0_pins_2_o_poe),
    .gpio_0_pins_3_o_oval                                                      (gpio_0_pins_3_o_oval),
    .gpio_0_pins_3_o_oe                                                        (gpio_0_pins_3_o_oe),
    .gpio_0_pins_3_o_ie                                                        (gpio_0_pins_3_o_ie),
    .gpio_0_pins_3_o_pue                                                       (gpio_0_pins_3_o_pue),
    .gpio_0_pins_3_o_ds                                                        (gpio_0_pins_3_o_ds),
    .gpio_0_pins_3_o_ds1                                                       (gpio_0_pins_3_o_ds1),
    .gpio_0_pins_3_o_poe                                                       (gpio_0_pins_3_o_poe),
    .gpio_0_pins_4_o_oval                                                      (gpio_0_pins_4_o_oval),
    .gpio_0_pins_4_o_oe                                                        (gpio_0_pins_4_o_oe),
    .gpio_0_pins_4_o_ie                                                        (gpio_0_pins_4_o_ie),
    .gpio_0_pins_4_o_pue                                                       (gpio_0_pins_4_o_pue),
    .gpio_0_pins_4_o_ds                                                        (gpio_0_pins_4_o_ds),
    .gpio_0_pins_4_o_ds1                                                       (gpio_0_pins_4_o_ds1),
    .gpio_0_pins_4_o_poe                                                       (gpio_0_pins_4_o_poe),
    .gpio_0_pins_5_o_oval                                                      (gpio_0_pins_5_o_oval),
    .gpio_0_pins_5_o_oe                                                        (gpio_0_pins_5_o_oe),
    .gpio_0_pins_5_o_ie                                                        (gpio_0_pins_5_o_ie),
    .gpio_0_pins_5_o_pue                                                       (gpio_0_pins_5_o_pue),
    .gpio_0_pins_5_o_ds                                                        (gpio_0_pins_5_o_ds),
    .gpio_0_pins_5_o_ds1                                                       (gpio_0_pins_5_o_ds1),
    .gpio_0_pins_5_o_poe                                                       (gpio_0_pins_5_o_poe),
    .gpio_0_pins_6_o_oval                                                      (gpio_0_pins_6_o_oval),
    .gpio_0_pins_6_o_oe                                                        (gpio_0_pins_6_o_oe),
    .gpio_0_pins_6_o_ie                                                        (gpio_0_pins_6_o_ie),
    .gpio_0_pins_6_o_pue                                                       (gpio_0_pins_6_o_pue),
    .gpio_0_pins_6_o_ds                                                        (gpio_0_pins_6_o_ds),
    .gpio_0_pins_6_o_ds1                                                       (gpio_0_pins_6_o_ds1),
    .gpio_0_pins_6_o_poe                                                       (gpio_0_pins_6_o_poe),
    .gpio_0_pins_7_o_oval                                                      (gpio_0_pins_7_o_oval),
    .gpio_0_pins_7_o_oe                                                        (gpio_0_pins_7_o_oe),
    .gpio_0_pins_7_o_ie                                                        (gpio_0_pins_7_o_ie),
    .gpio_0_pins_7_o_pue                                                       (gpio_0_pins_7_o_pue),
    .gpio_0_pins_7_o_ds                                                        (gpio_0_pins_7_o_ds),
    .gpio_0_pins_7_o_ds1                                                       (gpio_0_pins_7_o_ds1),
    .gpio_0_pins_7_o_poe                                                       (gpio_0_pins_7_o_poe),
    .qspi_0_sck                                                                (qspi_0_sck),
    .qspi_0_dq_0_o                                                             (qspi_0_dq_0_o),
    .qspi_0_dq_0_ie                                                            (qspi_0_dq_0_ie),
    .qspi_0_dq_0_oe                                                            (qspi_0_dq_0_oe),
    .qspi_0_dq_1_o                                                             (qspi_0_dq_1_o),
    .qspi_0_dq_1_ie                                                            (qspi_0_dq_1_ie),
    .qspi_0_dq_1_oe                                                            (qspi_0_dq_1_oe),
    .qspi_0_dq_2_o                                                             (qspi_0_dq_2_o),
    .qspi_0_dq_2_ie                                                            (qspi_0_dq_2_ie),
    .qspi_0_dq_2_oe                                                            (qspi_0_dq_2_oe),
    .qspi_0_dq_3_o                                                             (qspi_0_dq_3_o),
    .qspi_0_dq_3_ie                                                            (qspi_0_dq_3_ie),
    .qspi_0_dq_3_oe                                                            (qspi_0_dq_3_oe),
    .qspi_0_cs_0                                                               (qspi_0_cs_0),
    .spi_0_sck                                                                 (spi_0_sck),
    .spi_0_dq_0_o                                                              (spi_0_dq_0_o),
    .spi_0_dq_0_ie                                                             (spi_0_dq_0_ie),
    .spi_0_dq_0_oe                                                             (spi_0_dq_0_oe),
    .spi_0_dq_1_o                                                              (spi_0_dq_1_o),
    .spi_0_dq_1_ie                                                             (spi_0_dq_1_ie),
    .spi_0_dq_1_oe                                                             (spi_0_dq_1_oe),
    .spi_0_dq_2_o                                                              (spi_0_dq_2_o),
    .spi_0_dq_2_ie                                                             (spi_0_dq_2_ie),
    .spi_0_dq_2_oe                                                             (spi_0_dq_2_oe),
    .spi_0_dq_3_o                                                              (spi_0_dq_3_o),
    .spi_0_dq_3_ie                                                             (spi_0_dq_3_ie),
    .spi_0_dq_3_oe                                                             (spi_0_dq_3_oe),
    .spi_0_cs_0                                                                (spi_0_cs_0)
  );
  
  ResetCatchAndSync_d3 system_debug_systemjtag_reset_catcher (	// @[ResetCatchAndSync.scala:39:28]
    .clock         (_iocell_jtag_TCK_i),	// @[IOCell.scala:111:23]
    .reset         (_system_auto_subsystem_cbus_fixedClockNode_out_reset),	// @[ChipTop.scala:28:35]
    .io_sync_reset (_system_debug_systemjtag_reset_catcher_io_sync_reset)
  );
  AsyncResetSynchronizerShiftReg_w1_d3_i0 debug_reset_syncd_debug_reset_sync (	// @[ShiftReg.scala:45:23]
    .clock (_system_auto_subsystem_cbus_fixedClockNode_out_clock),	// @[ChipTop.scala:28:35]
    .reset (_system_debug_systemjtag_reset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .io_d  (1'h1),	// @[IOCell.scala:235:30]
    .io_q  (_debug_reset_syncd_debug_reset_sync_io_q)
  );
  ResetSynchronizerShiftReg_w1_d3_i0 dmactiveAck_dmactiveAck (	// @[ShiftReg.scala:45:23]
    .clock (_system_auto_subsystem_cbus_fixedClockNode_out_clock),	// @[ChipTop.scala:28:35]
    .reset (~_debug_reset_syncd_debug_reset_sync_io_q),	// @[Periphery.scala:287:40, ShiftReg.scala:45:23]
    .io_d  (_system_debug_dmactive),	// @[ChipTop.scala:28:35]
    .io_q  (_dmactiveAck_dmactiveAck_io_q)
  );
  
  // JTAG
  assign jtag_TDO = _system_debug_systemjtag_jtag_TDO_data;
  assign _iocell_jtag_TDI_i = jtag_TDI;
  assign _iocell_jtag_TMS_i = jtag_TMS;
  assign _iocell_jtag_TCK_i = jtag_TCK;

  // Serial
  assign _iocell_serial_tl_bits_out_bits_pad = _system_serial_tl_bits_out_bits[0];
  assign _iocell_serial_tl_bits_out_bits_1_pad = _system_serial_tl_bits_out_bits[1];
  assign _iocell_serial_tl_bits_out_bits_2_pad = _system_serial_tl_bits_out_bits[2];
  assign _iocell_serial_tl_bits_out_bits_3_pad = _system_serial_tl_bits_out_bits[3];
  assign serial_tl_bits_out_valid = _system_serial_tl_bits_out_valid;
  assign _iocell_serial_tl_bits_out_ready_i = serial_tl_bits_out_ready;

  assign _iocell_serial_tl_bits_in_bits_i =  serial_tl_bits_in_bits[0]; 
  assign _iocell_serial_tl_bits_in_bits_1_i = serial_tl_bits_in_bits[1];
  assign _iocell_serial_tl_bits_in_bits_2_i = serial_tl_bits_in_bits[2];
  assign _iocell_serial_tl_bits_in_bits_3_i = serial_tl_bits_in_bits[3];
  assign _iocell_serial_tl_bits_in_valid_i = serial_tl_bits_in_valid;
  assign serial_tl_bits_in_ready = _system_serial_tl_bits_in_ready;

  assign _iocell_serial_tl_clock_i = serial_tl_clock;
    
  assign serial_tl_bits_out_bits = {_iocell_serial_tl_bits_out_bits_3_pad, _iocell_serial_tl_bits_out_bits_2_pad, _iocell_serial_tl_bits_out_bits_1_pad, _iocell_serial_tl_bits_out_bits_pad};	// @[Cat.scala:33:92, IOCell.scala:112:24]
  assign gpio_0_pins_0_o_ps = 1'h0;	// @[ResetCatchAndSync.scala:39:28]
  assign gpio_0_pins_1_o_ps = 1'h0;	// @[ResetCatchAndSync.scala:39:28]
  assign gpio_0_pins_2_o_ps = 1'h0;	// @[ResetCatchAndSync.scala:39:28]
  assign gpio_0_pins_3_o_ps = 1'h0;	// @[ResetCatchAndSync.scala:39:28]
  assign gpio_0_pins_4_o_ps = 1'h0;	// @[ResetCatchAndSync.scala:39:28]
  assign gpio_0_pins_5_o_ps = 1'h0;	// @[ResetCatchAndSync.scala:39:28]
  assign gpio_0_pins_6_o_ps = 1'h0;	// @[ResetCatchAndSync.scala:39:28]
  assign gpio_0_pins_7_o_ps = 1'h0;	// @[ResetCatchAndSync.scala:39:28]
endmodule

