set_property PACKAGE_PIN {E3} [get_ports {sys_clock}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sys_clock}]
set_property CLOCK_DEDICATED_ROUTE {FALSE} [get_nets [get_ports {jtag_jtag_TCK}]]
set_property PACKAGE_PIN {D4} [get_ports {jtag_jtag_TDI}]
set_property IOSTANDARD {LVCMOS33} [get_ports {jtag_jtag_TDI}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDI}]
set_property PACKAGE_PIN {D3} [get_ports {jtag_jtag_TMS}]
set_property IOSTANDARD {LVCMOS33} [get_ports {jtag_jtag_TMS}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TMS}]
set_property PACKAGE_PIN {F4} [get_ports {jtag_jtag_TCK}]
set_property IOSTANDARD {LVCMOS33} [get_ports {jtag_jtag_TCK}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TCK}]
set_property PACKAGE_PIN {F3} [get_ports {jtag_jtag_TDO}]
set_property IOSTANDARD {LVCMOS33} [get_ports {jtag_jtag_TDO}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDO}]
set_property PACKAGE_PIN {E2} [get_ports {jtag_srst_n}]
set_property IOSTANDARD {LVCMOS33} [get_ports {jtag_srst_n}]
set_property PULLUP {TRUE} [get_ports {jtag_srst_n}]
set_property PACKAGE_PIN {A9} [get_ports {uart_rxd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_rxd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_rxd}]]]
set_property PACKAGE_PIN {D10} [get_ports {uart_txd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_txd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_txd}]]]
set_property PACKAGE_PIN {D2} [get_ports {uart2_rxd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart2_rxd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart2_rxd}]]]
set_property PACKAGE_PIN {H2} [get_ports {uart2_txd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart2_txd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart2_txd}]]]
set_property PACKAGE_PIN {A8} [get_ports {gpio_gpio_0}]
set_property IOSTANDARD {LVCMOS33} [get_ports {gpio_gpio_0}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {gpio_gpio_0}]]]
set_property PACKAGE_PIN {C11} [get_ports {gpio_gpio_1}]
set_property IOSTANDARD {LVCMOS33} [get_ports {gpio_gpio_1}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {gpio_gpio_1}]]]
set_property PACKAGE_PIN {C10} [get_ports {gpio_gpio_2}]
set_property IOSTANDARD {LVCMOS33} [get_ports {gpio_gpio_2}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {gpio_gpio_2}]]]
set_property PACKAGE_PIN {A10} [get_ports {gpio_gpio_3}]
set_property IOSTANDARD {LVCMOS33} [get_ports {gpio_gpio_3}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {gpio_gpio_3}]]]
set_property PACKAGE_PIN {E1} [get_ports {gpio_gpio_4}]
set_property IOSTANDARD {LVCMOS33} [get_ports {gpio_gpio_4}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {gpio_gpio_4}]]]
set_property PACKAGE_PIN {F6} [get_ports {gpio_gpio_5}]
set_property IOSTANDARD {LVCMOS33} [get_ports {gpio_gpio_5}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {gpio_gpio_5}]]]
set_property PACKAGE_PIN {G6} [get_ports {gpio_gpio_6}]
set_property IOSTANDARD {LVCMOS33} [get_ports {gpio_gpio_6}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {gpio_gpio_6}]]]
set_property PACKAGE_PIN {G4} [get_ports {gpio_gpio_7}]
set_property IOSTANDARD {LVCMOS33} [get_ports {gpio_gpio_7}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {gpio_gpio_7}]]]
set_property PACKAGE_PIN {D12} [get_ports {sdio_spi_clk}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_clk}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_clk}]]]
set_property PACKAGE_PIN {B11} [get_ports {sdio_spi_cs}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_cs}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_cs}]]]
set_property PACKAGE_PIN {A11} [get_ports {sdio_spi_dat_0}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_dat_0}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_dat_0}]]]
set_property PACKAGE_PIN {D13} [get_ports {sdio_spi_dat_1}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_dat_1}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_dat_1}]]]
set_property PACKAGE_PIN {B18} [get_ports {sdio_spi_dat_2}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_dat_2}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_dat_2}]]]
set_property PACKAGE_PIN {G13} [get_ports {sdio_spi_dat_3}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sdio_spi_dat_3}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_spi_dat_3}]]]
set_property PULLUP {TRUE} [get_ports {sdio_spi_cs}]
set_property PULLUP {TRUE} [get_ports {sdio_spi_dat_0}]
set_property PULLUP {TRUE} [get_ports {sdio_spi_dat_1}]
set_property PULLUP {TRUE} [get_ports {sdio_spi_dat_2}]
set_property PULLUP {TRUE} [get_ports {sdio_spi_dat_3}]
set_property PACKAGE_PIN {E15} [get_ports {flash_qspi_cs}]
set_property IOSTANDARD {LVCMOS33} [get_ports {flash_qspi_cs}]
set_property PACKAGE_PIN {E16} [get_ports {flash_qspi_dq_0}]
set_property IOSTANDARD {LVCMOS33} [get_ports {flash_qspi_dq_0}]
set_property PACKAGE_PIN {D15} [get_ports {flash_qspi_dq_1}]
set_property IOSTANDARD {LVCMOS33} [get_ports {flash_qspi_dq_1}]
set_property PACKAGE_PIN {C15} [get_ports {flash_qspi_sck}]
set_property IOSTANDARD {LVCMOS33} [get_ports {flash_qspi_sck}]
set_property PACKAGE_PIN {K15} [get_ports {flash_qspi_dq_2}]
set_property IOSTANDARD {LVCMOS33} [get_ports {flash_qspi_dq_2}]
set_property PACKAGE_PIN {J15} [get_ports {flash_qspi_dq_3}]
set_property IOSTANDARD {LVCMOS33} [get_ports {flash_qspi_dq_3}]
set_property PULLUP {TRUE} [get_ports {flash_qspi_dq_0}]
set_property PULLUP {TRUE} [get_ports {flash_qspi_dq_1}]
set_property PULLUP {TRUE} [get_ports {flash_qspi_sck}]
set_property PULLUP {TRUE} [get_ports {flash_qspi_dq_2}]
set_property PULLUP {TRUE} [get_ports {flash_qspi_dq_3}]
set_property BOARD_PIN {reset} [get_ports {reset}]
